<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table('countries')->insert([
            ['code' => 'AF', 'name' => 'Afghanistan', 'order_number' => 1],
            ['code' => 'AL', 'name' => 'Albania', 'order_number' => 2],
            ['code' => 'DZ', 'name' => 'Algeria', 'order_number' => 3],
            ['code' => 'DS', 'name' => 'American Samoa', 'order_number' => 4],
            ['code' => 'AD', 'name' => 'Andorra', 'order_number' => 5],
            ['code' => 'AO', 'name' => 'Angola', 'order_number' => 6],
            ['code' => 'AI', 'name' => 'Anguilla', 'order_number' => 7],
            ['code' => 'AQ', 'name' => 'Antarctica', 'order_number' => 8],
            ['code' => 'AG', 'name' => 'Antigua and Barbuda', 'order_number' => 9],
            ['code' => 'AR', 'name' => 'Argentina', 'order_number' => 10],
            ['code' => 'AM', 'name' => 'Armenia', 'order_number' => 11],
            ['code' => 'AW', 'name' => 'Aruba', 'order_number' => 12],
            ['code' => 'AU', 'name' => 'Australia', 'order_number' => 13],
            ['code' => 'AT', 'name' => 'Austria', 'order_number' => 14],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'order_number' => 15],
            ['code' => 'BS', 'name' => 'Bahamas', 'order_number' => 16],
            ['code' => 'BH', 'name' => 'Bahrain', 'order_number' => 17],
            ['code' => 'BD', 'name' => 'Bangladesh', 'order_number' => 18],
            ['code' => 'BB', 'name' => 'Barbados', 'order_number' => 19],
            ['code' => 'BY', 'name' => 'Belarus', 'order_number' => 20],
            ['code' => 'BE', 'name' => 'Belgium', 'order_number' => 21],
            ['code' => 'BZ', 'name' => 'Belize', 'order_number' => 22],
            ['code' => 'BJ', 'name' => 'Benin', 'order_number' => 23],
            ['code' => 'BM', 'name' => 'Bermuda', 'order_number' => 24],
            ['code' => 'BT', 'name' => 'Bhutan', 'order_number' => 25],
            ['code' => 'BO', 'name' => 'Bolivia', 'order_number' => 26],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'order_number' => 27],
            ['code' => 'BW', 'name' => 'Botswana', 'order_number' => 28],
            ['code' => 'BV', 'name' => 'Bouvet Island', 'order_number' => 29],
            ['code' => 'BR', 'name' => 'Brazil', 'order_number' => 30],
            ['code' => 'IO', 'name' => 'British Indian Ocean Territory', 'order_number' => 31],
            ['code' => 'BN', 'name' => 'Brunei Darussalam', 'order_number' => 32],
            ['code' => 'BG', 'name' => 'Bulgaria', 'order_number' => 33],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'order_number' => 34],
            ['code' => 'BI', 'name' => 'Burundi', 'order_number' => 35],
            ['code' => 'KH', 'name' => 'Cambodia', 'order_number' => 36],
            ['code' => 'CM', 'name' => 'Cameroon', 'order_number' => 37],
            ['code' => 'CA', 'name' => 'Canada', 'order_number' => 38],
            ['code' => 'CV', 'name' => 'Cape Verde', 'order_number' => 39],
            ['code' => 'KY', 'name' => 'Cayman Islands', 'order_number' => 40],
            ['code' => 'CF', 'name' => 'Central African Republic', 'order_number' => 41],
            ['code' => 'TD', 'name' => 'Chad', 'order_number' => 42],
            ['code' => 'CL', 'name' => 'Chile', 'order_number' => 43],
            ['code' => 'CN', 'name' => 'China', 'order_number' => 44],
            ['code' => 'CX', 'name' => 'Christmas Island', 'order_number' => 45],
            ['code' => 'CC', 'name' => 'Cocos (Keeling) Islands', 'order_number' => 46],
            ['code' => 'CO', 'name' => 'Colombia', 'order_number' => 47],
            ['code' => 'KM', 'name' => 'Comoros', 'order_number' => 48],
            ['code' => 'CG', 'name' => 'Congo', 'order_number' => 49],
            ['code' => 'CK', 'name' => 'Cook Islands', 'order_number' => 50],
            ['code' => 'CR', 'name' => 'Costa Rica', 'order_number' => 51],
            ['code' => 'HR', 'name' => 'Croatia (Hrvatska)', 'order_number' => 52],
            ['code' => 'CU', 'name' => 'Cuba', 'order_number' => 53],
            ['code' => 'CY', 'name' => 'Cyprus', 'order_number' => 54],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'order_number' => 55],
            ['code' => 'DK', 'name' => 'Denmark', 'order_number' => 56],
            ['code' => 'DJ', 'name' => 'Djibouti', 'order_number' => 57],
            ['code' => 'DM', 'name' => 'Dominica', 'order_number' => 58],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'order_number' => 59],
            ['code' => 'TP', 'name' => 'East Timor', 'order_number' => 60],
            ['code' => 'EC', 'name' => 'Ecuador', 'order_number' => 61],
            ['code' => 'EG', 'name' => 'Egypt', 'order_number' => 62],
            ['code' => 'SV', 'name' => 'El Salvador', 'order_number' => 63],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'order_number' => 64],
            ['code' => 'ER', 'name' => 'Eritrea', 'order_number' => 65],
            ['code' => 'EE', 'name' => 'Estonia', 'order_number' => 66],
            ['code' => 'ET', 'name' => 'Ethiopia', 'order_number' => 67],
            ['code' => 'FK', 'name' => 'Falkland Islands (Malvinas)', 'order_number' => 68],
            ['code' => 'FO', 'name' => 'Faroe Islands', 'order_number' => 69],
            ['code' => 'FJ', 'name' => 'Fiji', 'order_number' => 70],
            ['code' => 'FI', 'name' => 'Finland', 'order_number' => 71],
            ['code' => 'FR', 'name' => 'France', 'order_number' => 72],
            ['code' => 'FX', 'name' => 'France, Metropolitan', 'order_number' => 73],
            ['code' => 'GF', 'name' => 'French Guiana', 'order_number' => 74],
            ['code' => 'PF', 'name' => 'French Polynesia', 'order_number' => 75],
            ['code' => 'TF', 'name' => 'French Southern Territories', 'order_number' => 76],
            ['code' => 'GA', 'name' => 'Gabon', 'order_number' => 77],
            ['code' => 'GM', 'name' => 'Gambia', 'order_number' => 78],
            ['code' => 'GE', 'name' => 'Georgia', 'order_number' => 79],
            ['code' => 'DE', 'name' => 'Germany', 'order_number' => 80],
            ['code' => 'GH', 'name' => 'Ghana', 'order_number' => 81],
            ['code' => 'GI', 'name' => 'Gibraltar', 'order_number' => 82],
            ['code' => 'GK', 'name' => 'Guernsey', 'order_number' => 83],
            ['code' => 'GR', 'name' => 'Greece', 'order_number' => 84],
            ['code' => 'GL', 'name' => 'Greenland', 'order_number' => 85],
            ['code' => 'GD', 'name' => 'Grenada', 'order_number' => 86],
            ['code' => 'GP', 'name' => 'Guadeloupe', 'order_number' => 87],
            ['code' => 'GU', 'name' => 'Guam', 'order_number' => 88],
            ['code' => 'GT', 'name' => 'Guatemala', 'order_number' => 89],
            ['code' => 'GN', 'name' => 'Guinea', 'order_number' => 90],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'order_number' => 91],
            ['code' => 'GY', 'name' => 'Guyana', 'order_number' => 92],
            ['code' => 'HT', 'name' => 'Haiti', 'order_number' => 93],
            ['code' => 'HM', 'name' => 'Heard and Mc Donald Islands', 'order_number' => 94],
            ['code' => 'HN', 'name' => 'Honduras', 'order_number' => 95],
            ['code' => 'HK', 'name' => 'Hong Kong', 'order_number' => 96],
            ['code' => 'HU', 'name' => 'Hungary', 'order_number' => 97],
            ['code' => 'IS', 'name' => 'Iceland', 'order_number' => 98],
            ['code' => 'IN', 'name' => 'India', 'order_number' => 99],
            ['code' => 'IM', 'name' => 'Isle of Man', 'order_number' => 100],
            ['code' => 'ID', 'name' => 'Indonesia', 'order_number' => 101],
            ['code' => 'IR', 'name' => 'Iran (Islamic Republic of)', 'order_number' => 102],
            ['code' => 'IQ', 'name' => 'Iraq', 'order_number' => 103],
            ['code' => 'IE', 'name' => 'Ireland', 'order_number' => 104],
            ['code' => 'IL', 'name' => 'Israel', 'order_number' => 105],
            ['code' => 'IT', 'name' => 'Italy', 'order_number' => 106],
            ['code' => 'CI', 'name' => 'Ivory Coast', 'order_number' => 107],
            ['code' => 'JE', 'name' => 'Jersey', 'order_number' => 108],
            ['code' => 'JM', 'name' => 'Jamaica', 'order_number' => 109],
            ['code' => 'JP', 'name' => 'Japan', 'order_number' => 110],
            ['code' => 'JO', 'name' => 'Jordan', 'order_number' => 111],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'order_number' => 112],
            ['code' => 'KE', 'name' => 'Kenya', 'order_number' => 113],
            ['code' => 'KI', 'name' => 'Kiribati', 'order_number' => 114],
            ['code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of', 'order_number' => 115],
            ['code' => 'KR', 'name' => 'Korea, Republic of', 'order_number' => 116],
            ['code' => 'XK', 'name' => 'Kosovo', 'order_number' => 117],
            ['code' => 'KW', 'name' => 'Kuwait', 'order_number' => 118],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'order_number' => 119],
            ['code' => 'LA', 'name' => 'Lao People\'s Democratic Republic', 'order_number' => 120],
            ['code' => 'LV', 'name' => 'Latvia', 'order_number' => 121],
            ['code' => 'LB', 'name' => 'Lebanon', 'order_number' => 122],
            ['code' => 'LS', 'name' => 'Lesotho', 'order_number' => 123],
            ['code' => 'LR', 'name' => 'Liberia', 'order_number' => 124],
            ['code' => 'LY', 'name' => 'Libyan Arab Jamahiriya', 'order_number' => 125],
            ['code' => 'LI', 'name' => 'Liechtenstein', 'order_number' => 126],
            ['code' => 'LT', 'name' => 'Lithuania', 'order_number' => 127],
            ['code' => 'LU', 'name' => 'Luxembourg', 'order_number' => 128],
            ['code' => 'MO', 'name' => 'Macau', 'order_number' => 129],
            ['code' => 'MK', 'name' => 'Macedonia', 'order_number' => 130],
            ['code' => 'MG', 'name' => 'Madagascar', 'order_number' => 131],
            ['code' => 'MW', 'name' => 'Malawi', 'order_number' => 132],
            ['code' => 'MY', 'name' => 'Malaysia', 'order_number' => 133],
            ['code' => 'MV', 'name' => 'Maldives', 'order_number' => 134],
            ['code' => 'ML', 'name' => 'Mali', 'order_number' => 135],
            ['code' => 'MT', 'name' => 'Malta', 'order_number' => 136],
            ['code' => 'MH', 'name' => 'Marshall Islands', 'order_number' => 137],
            ['code' => 'MQ', 'name' => 'Martinique', 'order_number' => 138],
            ['code' => 'MR', 'name' => 'Mauritania', 'order_number' => 139],
            ['code' => 'MU', 'name' => 'Mauritius', 'order_number' => 140],
            ['code' => 'TY', 'name' => 'Mayotte', 'order_number' => 141],
            ['code' => 'MX', 'name' => 'Mexico', 'order_number' => 142],
            ['code' => 'FM', 'name' => 'Micronesia, Federated States of', 'order_number' => 143],
            ['code' => 'MD', 'name' => 'Moldova, Republic of', 'order_number' => 144],
            ['code' => 'MC', 'name' => 'Monaco', 'order_number' => 145],
            ['code' => 'MN', 'name' => 'Mongolia', 'order_number' => 146],
            ['code' => 'ME', 'name' => 'Montenegro', 'order_number' => 147],
            ['code' => 'MS', 'name' => 'Montserrat', 'order_number' => 148],
            ['code' => 'MA', 'name' => 'Morocco', 'order_number' => 149],
            ['code' => 'MZ', 'name' => 'Mozambique', 'order_number' => 150],
            ['code' => 'MM', 'name' => 'Myanmar', 'order_number' => 151],
            ['code' => 'NA', 'name' => 'Namibia', 'order_number' => 152],
            ['code' => 'NR', 'name' => 'Nauru', 'order_number' => 153],
            ['code' => 'NP', 'name' => 'Nepal', 'order_number' => 154],
            ['code' => 'NL', 'name' => 'Netherlands', 'order_number' => 155],
            ['code' => 'AN', 'name' => 'Netherlands Antilles', 'order_number' => 156],
            ['code' => 'NC', 'name' => 'New Caledonia', 'order_number' => 157],
            ['code' => 'NZ', 'name' => 'New Zealand', 'order_number' => 158],
            ['code' => 'NI', 'name' => 'Nicaragua', 'order_number' => 159],
            ['code' => 'NE', 'name' => 'Niger', 'order_number' => 160],
            ['code' => 'NG', 'name' => 'Nigeria', 'order_number' => 161],
            ['code' => 'NU', 'name' => 'Niue', 'order_number' => 162],
            ['code' => 'NF', 'name' => 'Norfolk Island', 'order_number' => 163],
            ['code' => 'MP', 'name' => 'Northern Mariana Islands', 'order_number' => 164],
            ['code' => 'NO', 'name' => 'Norway', 'order_number' => 165],
            ['code' => 'OM', 'name' => 'Oman', 'order_number' => 166],
            ['code' => 'PK', 'name' => 'Pakistan', 'order_number' => 167],
            ['code' => 'PW', 'name' => 'Palau', 'order_number' => 168],
            ['code' => 'PS', 'name' => 'Palestine', 'order_number' => 169],
            ['code' => 'PA', 'name' => 'Panama', 'order_number' => 170],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'order_number' => 171],
            ['code' => 'PY', 'name' => 'Paraguay', 'order_number' => 172],
            ['code' => 'PE', 'name' => 'Peru', 'order_number' => 173],
            ['code' => 'PH', 'name' => 'Philippines', 'order_number' => 174],
            ['code' => 'PN', 'name' => 'Pitcairn', 'order_number' => 175],
            ['code' => 'PL', 'name' => 'Poland', 'order_number' => 176],
            ['code' => 'PT', 'name' => 'Portugal', 'order_number' => 177],
            ['code' => 'PR', 'name' => 'Puerto Rico', 'order_number' => 178],
            ['code' => 'QA', 'name' => 'Qatar', 'order_number' => 179],
            ['code' => 'RE', 'name' => 'Reunion', 'order_number' => 180],
            ['code' => 'RO', 'name' => 'Romania', 'order_number' => 181],
            ['code' => 'RU', 'name' => 'Russian Federation', 'order_number' => 182],
            ['code' => 'RW', 'name' => 'Rwanda', 'order_number' => 183],
            ['code' => 'KN', 'name' => 'Saint Kitts and Nevis', 'order_number' => 184],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'order_number' => 185],
            ['code' => 'VC', 'name' => 'Saint Vincent and the Grenadines', 'order_number' => 186],
            ['code' => 'WS', 'name' => 'Samoa', 'order_number' => 187],
            ['code' => 'SM', 'name' => 'San Marino', 'order_number' => 188],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'order_number' => 189],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'order_number' => 190],
            ['code' => 'SN', 'name' => 'Senegal', 'order_number' => 191],
            ['code' => 'RS', 'name' => 'Serbia', 'order_number' => 192],
            ['code' => 'SC', 'name' => 'Seychelles', 'order_number' => 193],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'order_number' => 194],
            ['code' => 'SG', 'name' => 'Singapore', 'order_number' => 195],
            ['code' => 'SK', 'name' => 'Slovakia', 'order_number' => 196],
            ['code' => 'SI', 'name' => 'Slovenia', 'order_number' => 197],
            ['code' => 'SB', 'name' => 'Solomon Islands', 'order_number' => 198],
            ['code' => 'SO', 'name' => 'Somalia', 'order_number' => 199],
            ['code' => 'ZA', 'name' => 'South Africa', 'order_number' => 200],
            ['code' => 'GS', 'name' => 'South Georgia South Sandwich Islands', 'order_number' => 202],
            ['code' => 'ES', 'name' => 'Spain', 'order_number' => 202],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'order_number' => 203],
            ['code' => 'SH', 'name' => 'St. Helena', 'order_number' => 204],
            ['code' => 'PM', 'name' => 'St. Pierre and Miquelon', 'order_number' => 205],
            ['code' => 'SD', 'name' => 'Sudan', 'order_number' => 206],
            ['code' => 'SR', 'name' => 'Suriname', 'order_number' => 207],
            ['code' => 'SJ', 'name' => 'Svalbard and Jan Mayen Islands', 'order_number' => 208],
            ['code' => 'SZ', 'name' => 'Swaziland', 'order_number' => 209],
            ['code' => 'SE', 'name' => 'Sweden', 'order_number' => 210],
            ['code' => 'CH', 'name' => 'Switzerland', 'order_number' => 211],
            ['code' => 'SY', 'name' => 'Syrian Arab Republic', 'order_number' => 212],
            ['code' => 'TW', 'name' => 'Taiwan', 'order_number' => 213],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'order_number' => 214],
            ['code' => 'TZ', 'name' => 'Tanzania, United Republic of', 'order_number' => 215],
            ['code' => 'TH', 'name' => 'Thailand', 'order_number' => 216],
            ['code' => 'TG', 'name' => 'Togo', 'order_number' => 217],
            ['code' => 'TK', 'name' => 'Tokelau', 'order_number' => 218],
            ['code' => 'TO', 'name' => 'Tonga', 'order_number' => 219],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'order_number' => 220],
            ['code' => 'TN', 'name' => 'Tunisia', 'order_number' => 221],
            ['code' => 'TR', 'name' => 'Turkey', 'order_number' => 222],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'order_number' => 223],
            ['code' => 'TC', 'name' => 'Turks and Caicos Islands', 'order_number' => 224],
            ['code' => 'TV', 'name' => 'Tuvalu', 'order_number' => 225],
            ['code' => 'UG', 'name' => 'Uganda', 'order_number' => 226],
            ['code' => 'UA', 'name' => 'Ukraine', 'order_number' => 227],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'order_number' => 228],
            ['code' => 'GB', 'name' => 'United Kingdom', 'order_number' => 229],
            ['code' => 'US', 'name' => 'United States', 'order_number' => 230],
            ['code' => 'UM', 'name' => 'United States minor outlying islands', 'order_number' => 231],
            ['code' => 'UY', 'name' => 'Uruguay', 'order_number' => 232],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'order_number' => 233],
            ['code' => 'VU', 'name' => 'Vanuatu', 'order_number' => 234],
            ['code' => 'VA', 'name' => 'Vatican City State', 'order_number' => 235],
            ['code' => 'VE', 'name' => 'Venezuela', 'order_number' => 236],
            ['code' => 'VN', 'name' => 'Vietnam', 'order_number' => 237],
            ['code' => 'VG', 'name' => 'Virgin Islands (British)', 'order_number' => 238],
            ['code' => 'VI', 'name' => 'Virgin Islands (U.S.)', 'order_number' => 239],
            ['code' => 'WF', 'name' => 'Wallis and Futuna Islands', 'order_number' => 240],
            ['code' => 'EH', 'name' => 'Western Sahara', 'order_number' => 241],
            ['code' => 'YE', 'name' => 'Yemen', 'order_number' => 242],
            ['code' => 'ZR', 'name' => 'Zaire', 'order_number' => 243],
            ['code' => 'ZM', 'name' => 'Zambia', 'order_number' => 244],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'order_number' => 245]
        ]);
    }
}
